spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/pa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: irany
    hikari:
      connection-timeout: 30000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml